// <auto-generated />
using System;
using MelonBot.Bots.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MelonBot.Bots.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20210124234710_InitializeSqliteDB")]
    partial class InitializeSqliteDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MelonBot.Bots.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DripCooldown")
                        .HasColumnType("TEXT");

                    b.Property<string>("DripInventory")
                        .HasColumnType("TEXT");

                    b.Property<int>("DripScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GambleCooldown")
                        .HasColumnType("TEXT");

                    b.Property<int>("GambleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GambleTickets")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserIconURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("guildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
